### PR TITLE
Add export option to ClassURLWriter

### PR DESCRIPTION
**Pull request by RobbieFernandez**
Hi, really nice library! I'm using it to generate a JS class for a client that lives outside of my Django codebase. So it would be ideal if the class that gets generated also gets exported. This PR adds that in in the simplest way I could think of. Not 100% sure what the best way to do exports is in es5, please let me know if there's a better option. 

Also happy to add tests if you'd like this feature merged :smile:

### CODE REVIEW

**Comment by RobbieFernandez** [comment]
Hi Brian. I hand't though of that but that is all I would need actually. I'm happy to do it that way and have this PR closed then. Thanks!

**Comment by bckohan** [comment]
If you wanted to resubmit this I would pull it into version 2. Looks like the fork was deleted.

**Comment by RobbieFernandez** [comment]
@bckohan I'm happy to resubmit this if you like. I deleted the branch and closed the PR since I was able to achieve the same result with your suggestion without this code change

**Comment by bckohan** [comment]
@RobbieFernandez please do!

**Pull request closed without merging**
